version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - '3000:80'
